### ISSUE TITLE
missing parent of lightstep-tracer-jre in Maven Central

### ISSUE THREAD

**Issue by malafeev** [lightstep/lightstep-tracer-java#121]
version `0.12.10`
parent of `lightstep-tracer-jre` is `lightstep-tracer-java`
but `lightstep-tracer-java` doesn't exist in Maven Central

Therefore I cannot use `lightstep-tracer-jre`:
```
[ERROR]: Failed to collect dependencies at com.lightstep.tracer:lightstep-tracer-jre:jar:0.12.10: 
Failed to read artifact descriptor for com.lightstep.tracer:lightstep-tracer-jre:jar:0.12.10: 
Could not find artifact com.lightstep.tracer:lightstep-tracer-java:pom:0.12.10 in central (https://repo.maven.apache.org/maven2)
```

**Comment by frenchfrywpepper** [comment]
Why does it need to be found in Maven central? lightstep-tracer-java 0.12.10 is in the same project as lightstep-tracer-jre.

**Comment by frenchfrywpepper** [comment]
Okay, I see the issue and I'm working on a fix. Thanks @malafeev

**Comment by frenchfrywpepper** [comment]
Version 0.12.14 addresses this issue. I tested with rxjava-feign-hystrix-failure and confirmed it's working.
