### ISSUE TITLE
Java tracer throws NumberFormatException when span context headers are present but empty

### ISSUE THREAD

**Issue by parker-edwards** [lightstep/lightstep-tracer-java#163]
When `ot-tracer-spanid` and/or `ot-tracer-traceid` are present in headers but are empty, `tracer.extract` throws a `NumberFormatException (Zero length BigInteger)`

Versions:

"com.lightstep.tracer" % "java-common" % "0.15.8",
"com.lightstep.tracer" % "tracer-okhttp" % "0.15.8",
"com.lightstep.tracer" % "lightstep-tracer-jre" % "0.14.6"

**Comment by carlosalberto** [comment]
This should be fixed through https://github.com/lightstep/lightstep-tracer-java-common/commit/14cc7fe8ed3f15fc0f936ae2b2ac24494b46db3e - we should roll out a release soon of it, I expect? @parker-edwards ;)

**Comment by carlosalberto** [comment]
Closing as merged and released with fix ;)
