### ISSUE TITLE
add possibility to select the client provider in the bundle

### ISSUE THREAD

**Issue by zeitlinger** [lightstep/lightstep-tracer-java#224]
lightstep-tracer-jre-bundle currently uses HTTP as the client provider - and it's not possible to change that.

**Comment by zeitlinger** [comment]
I'll create a PR once https://github.com/lightstep/lightstep-tracer-java-common/pull/116 is merged.

**Comment by arpit728** [comment]
https://github.com/lightstep/lightstep-tracer-java/issues/229
