### ISSUE TITLE
Span Sampling

### ISSUE THREAD

**Issue by mviamari** [lightstep/lightstep-tracer-java#228]
What is the recommended method for implementing sampling for this tracer? I'd like to implement sampling for my application in a manner that's supported by open-tracing, but I don't see exactly where those hooks might be in this tracer implementation.

My initial approach would be to use the open-tracing tag `SAMPLING_PRIORITY` to indicate the traces/spans that should be sampled, and then have the span reporter/collector simply skip sending those onto the satellite.  I think that part can be done here https://github.com/lightstep/lightstep-tracer-java-common/blob/master/common/src/main/java/com/lightstep/tracer/shared/AbstractTracer.java#L588.

However, I didn't see support for propagating the sampling tag across contexts. The current implementation appears to force the sampling tag to true (https://github.com/lightstep/lightstep-tracer-java-common/blob/ffea1c7f0caa8266fc54b9b44f0d1c0ad9fc6e98/common/src/main/java/com/lightstep/tracer/shared/TextMapPropagator.java#L27) but also there is no mechanism for using extract to check the parent span for a sampling tag. Additionally, the `SpanContext `doesn't have a sampled field (just `traceId`, `spanId` and `baggage`).

**Comment by carlosalberto** [comment]
Closing as we won't be implementing client side tracing for the time being. Please re-open or comment if this is still an issue @mviamari ;)
