### ISSUE TITLE
Using B3 Propagators with SpecialAgent ?

### ISSUE THREAD

**Issue by arpit728** [lightstep/lightstep-tracer-java#230]
I am using java-lightstep-tracer with special-agent, the problem here is that it lightstep-tracer uses OT propagator. All of my services use B3 Propagator, I couldn't find a way to enforce lightstep to use B3 Propagator. Below are the sample headers that are currently being sent out.

```
  'ot-tracer-spanid': '31397286a1497e1f, c459505d076d17a4',
  'ot-tracer-traceid': 'db4ed3b04ac07fa7, db4ed3b04ac07fa7',
  'ot-tracer-sampled': 'true, true',
```

**Comment by zeitlinger** [comment]
I think this is addressed by `ls.propagator=b3` - see [here](https://github.com/lightstep/lightstep-tracer-java/blob/master/lightstep-tracer-jre-bundle/src/main/java/com/lightstep/tracer/jre/TracerParameters.java#L138-L143) - which is available in specialagent v1.5.9

**Comment by zeitlinger** [comment]
This [PR](https://github.com/lightstep/lightstep-tracer-java/pull/235/files#diff-1b1b479e17589722feb221f6ea54da36R45) adds documentation for all parameters.

**Comment by carlosalberto** [comment]
Closed as we both support B3 and also documentation has been updated, as Gregor mentioned ;)
