### ISSUE TITLE
Project access tokens are logged

### ISSUE THREAD

**Issue by william-tran** [lightstep/lightstep-tracer-java#236]
```
Mar 25, 2020 2:50:36 PM com.lightstep.tracer.jre.TracerParameters getParameters
INFO: Retrieved Tracer parameter ls.accessToken=***REDACTED***
```
That's what it should print, but it prints out the actual access token, which is a security issue if you have more than one project.

**Comment by carlosalberto** [comment]
Hey @william-tran 

We'd like to log that the token was properly detected from the environment & system properties. Showing only the first and last characters, hiding all the chars in between would work for you? i.e. given a token `aaabbbcccddd`, log it as `aXXXXXXXXXXd`?

**Comment by carlosalberto** [comment]
(Or something similar - CircleCI for example, logs the last 3 chars only, so it would show `XXXXXXXXddd`)

**Comment by carlosalberto** [comment]
@malafeev think you could take this one?

**Comment by malafeev** [comment]
sure

**Comment by malafeev** [comment]
fixed via https://github.com/lightstep/lightstep-tracer-java/pull/245
