### ISSUE TITLE
Shape up the code for the bundle jar allowing collector selection

### ISSUE THREAD

**Issue by carlosalberto** [lightstep/lightstep-tracer-java#243]
After #235 was merged a few items are left to be done for `lightstep-jre-tracer-bundle`:

- [ ] Add a dependency to `collector-grpc` in `lightstep-jre-tracer-bundle` and make sure it works just fine.
- [ ] Shade related/important libraries that are brought as part of `collector-grpc`, similar to how we do that for the `shadow` artifact (many more libraries might need to be shaded).
- [ ] Consider shading `okhttp` libraries as well.

The idea is that users of the bundle jar do not get version conflicts when using `grpc` and related components (and `okhttp` to a minor degree).

**Comment by carlosalberto** [comment]
@malafeev Think you can take this one also? This one will require some digging and verifications here and there, but it's something we really need to have ;)

**Comment by malafeev** [comment]
sure!

**Comment by andrewhsu** [comment]
Looks like PR #244 is ready.

Note: also need to look into shading google protobuf later.
