### ISSUE TITLE
Exception not fully correctly logged

### ISSUE THREAD

**Issue by malafeev** [lightstep/lightstep-tracer-java#246]
From https://github.com/lightstep/lightstep-tracer-java-common/issues/144

Exception should be logged properly in `com.lightstep.tracer.jre.JRETracer` `printLogToConsole`

Blocked by https://github.com/lightstep/lightstep-tracer-java-common/issues/144

**Comment by malafeev** [comment]
done

**Comment by plum117** [comment]
Tx
