### ISSUE TITLE
android javadoc access denied

### ISSUE THREAD

**Issue by nicks** [lightstep/lightstep-tracer-java#38]
The README has a link to http://javadoc.io/doc/com.lightstep.tracer/lightstep-tracer-android/0.9.12

But when I go there, I just get an access denied error

```
AccessDeniedAccess DeniedF36786878036B65FMlgKh56ZP/U4I5G7faS6p7rJJVsBwEDWg+jy2r1nmLc8o5AuVtKty5JxJU0VQuU+E712Kf3hEX4=
```

**Comment by bcronin** [comment]
Thanks @nicks. Not sure what's going on there, but we'll look into it.

**Comment by danielamiao** [comment]
Even though the above link is still broken, the README link has been updated to reflect the newest version of Javadoc which works. Closing issue.
