### ISSUE TITLE
android build includes over 10K methods

### ISSUE THREAD

**Issue by nicks** [lightstep/lightstep-tracer-java#39]
Unfortunately, the Dex method limit on Android is 65K, so throwing away 10K for Lightstep is a non-starter for us right now.
https://developer.android.com/studio/build/multidex.html

I suspect the problem is that you're including Jackson, which we've found has major code-footprint and run-time performance problems on Android (because it uses reflection so heavily)

**Comment by bensigelman** [comment]
@nicks thanks for reporting this. The `jackson` dependency is used to convert arbitrary `Object`s to JSON for the logging API... as a matter of fact, the Key-Value logging scheme in OpenTracing-Java recently changed, and I was going to take on the work of updating both the JRE and Android Java libs to reflect those changes. In the process I will do my best to perform a `jackson`ectomy. ETA next week, though if this is urgent I can fast-track it.

**Comment by nicks** [comment]
It's not urgent.

ya, this is one of the most embarrassing things about android development. The Server-side java packaging approach of "try to handle all possible data types out of the box" falls down. Popular android libraries usually have a plugin model, and publish different converter plugins as different maven artifacts, see http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.squareup.retrofit2%22

**Comment by bensigelman** [comment]
Good to know, thanks for the pointer.

I understand that it's not _urgent_ per se, but presumably this does block prod Android integration... We will still try to turn something around soon. Thanks again for the report.

**Comment by bensigelman** [comment]
@nicks the Android (and JRE) artifacts no longer reference Jackson as of version `0.9.13`... better?

**Comment by nicks** [comment]
thanks! much better

**Comment by bensigelman** [comment]
@nicks great. I will close this for now. We will be moving from Thrift to GRPC this quarter which should hopefully help a bit more, btw.
