### ISSUE TITLE
Add TracerResolver

### ISSUE THREAD

**Issue by malafeev** [lightstep/lightstep-tracer-java#99]
https://github.com/opentracing-contrib/java-tracerresolver 

It could be used at least in [java-cassandra-driver](https://github.com/opentracing-contrib/java-cassandra-driver/)  when https://github.com/opentracing-contrib/java-cassandra-driver/issues/1 will be fixed.

**Comment by andrewhsu** [comment]
@malafeev talked with @carlosalberto at our weekly mtg, seems like this is not needed anymore
